version: '3'
services:
  api:
    build: api
    command: yarn dev
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./api:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development
      STANDUP_ROCKS_PORT: 3000
      STANDUP_ROCKS_PGHOST: db
      STANDUP_ROCKS_PGUSER: postgres
      STANDUP_ROCKS_PGDATABASE: standup
      STANDUP_ROCKS_PGPASSWORD: standup
      STANDUP_ROCKS_PGPORT: "5432"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: standup
      POSTGRES_USER: postgres
      POSTGRES_DB: standup
    ports:
      - '15432:5432'
