version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_SHA1
          cd api
          docker build -t bttf/capcal:latest -t bttf/capcal:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bttf/capcal:$TAG
          docker push bttf/capcal:latest
      - run: |
          TAG=$CIRCLE_SHA1
          cd plaid-bookkeeper
          docker build -t bttf/capcal-bookkeeper:latest -t bttf/capcal-bookkeeper:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bttf/capcal-bookkeeper:$TAG
          docker push bttf/capcal-bookkeeper:latest
      - run: |
          TAG=$CIRCLE_SHA1
          cd plaid-webhook-handler
          docker build -t bttf/capcal-webhook-handler:latest -t bttf/capcal-webhook-handler:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bttf/capcal-webhook-handler:$TAG
          docker push bttf/capcal-webhook-handler:latest
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy
          command: ./scripts/ci-deploy.sh
workflows:
  capcal-web-app:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
